pipeline {
    agent { label 'node' } 
    stages {
        stage('Build') { 
            steps {
                echo 'This is the build stage'
                echo "User is ${env.NAME1} ${env.NAME2}"
            }
        }
    }
}
