stage('pre-pipeline-check') {
  echo 'Checking commit message for corporate standard template'
  echo 'License check'
}

node() {
  try {
    git credentialsId: "${github_creds}" , url: "${github_repo}"
    
    def teamPipeline = readFile 'Jenkinsfile'
    evaluate teamPipeline
  } catch (err) {
    echo 'Could not load Jenkinsfile, skipping Jenkinsfile execution'
  }
}

stage('post-pipeline-check') {
  echo 'Running security scanner'
  echo 'Checking necessary sign offs'
}
