stage('pre-pipeline-check') {
  echo 'Checking commit message for corporate standard template'
  echo 'License check'
}

node() {
  try {
    git credentialsId: "${github_creds}" , url: "https://github.com/${github_owner}/${github_repo}"
    sh 'ls -l'
    def teamPipeline = readFile "${jenksfile_name}"
    evaluate teamPipeline
  } catch (err) {
    echo "Caught: ${err}"
    echo 'Could not load Jenkinsfile, skipping Jenkinsfile execution'
  }
}

stage('post-pipeline-check') {
  echo 'Running security scanner'
  echo 'Checking necessary sign offs'
}
