stage('pre-pipeline-check') {
  echo 'Checking commit message for corporate standard template'
  echo 'License check'
}

node() {
  try {
    def teamPipeline = readFile 'Jenkinsfile'
    evaluate teamPipeline
  } catch (err) {
    echo 'No Jenkinsfile detected, skipping Jenkinsfile execution'
  }
}

stage('post-pipeline-check') {
  echo 'Running security scanner'
  echo 'Checking necessary sign offs'
}
